### ISSUE TITLE
different plot than expected

### ISSUE THREAD

**Issue by pinkcreeper100** [alexhuntley/Plots#105]
equation: 5y=4x+10

in plots, it intersects the x axis at 2.5
in desmos, it intersects the x axis at -2.5

**Comment by ritamsaha00** [comment]
ok, you are right, it's giving the wrong result

![image](https://user-images.githubusercontent.com/69363775/210261204-a53a119b-a7db-43b5-86e8-f75104e5dd84.png)

![desmos-graph](https://user-images.githubusercontent.com/69363775/210261423-d2cdb21b-6858-452f-85e7-6579f15d8c40.svg)

**Comment by alexhuntley** [comment]
Fixed in 108cd3bee5085efcc2636495f236e591b468b245
