### ISSUE TITLE
Implicit equation for ellipse yields hyperbola (and vice versa)

### ISSUE THREAD

**Issue by lkstl** [alexhuntley/Plots#109]
![Bildschirmfoto vom 2023-01-17 14-51-48](https://user-images.githubusercontent.com/10185204/212916804-b19b6013-4e1b-4966-9ed6-f4446bb525b3.png)

The implicit equation $\frac{x^2}{a^2}+\frac{y^2}{b^2}=1$ is correctly plotted as an ellipse. Subtracting $\frac{x^2}{a^2}$ should not change the plot, however, $\frac{y^{2}}{b^{2}}=1-\frac{x^{2}}{a^{2}}$ is plotted as a hyperbola. For good measure I have thrown in further transformations of the equation (making it an explicit equation); they are displayed correctly.

Vice versa, the equation $\frac{x^2}{a^2}-\frac{y^2}{b^2}=1$ is correctly plotted as a hyperbola but the transformed equation $\frac{x^2}{a^2}=1+\frac{y^2}{b^2}$ becomes an ellipse (not shown in image).

**Comment by alexhuntley** [comment]
Thanks for spotting this!
