### ISSUE TITLE
readme: flatpak-pip-generator snippet does not work as-is

### ISSUE THREAD

**Issue by wbernard** [alexhuntley/Plots#11]
I followed the instructions and tried to use the extension-less pyhon file, but that didn't work:

> python3 flatpak-pip-generator --requirements-file=flatpak-requirements.txt --no-build-isolation

The snippet only worked for me after renaming the file and using this command:

> python3 flatpak-pip-generator.py --requirements-file=flatpak-requirements.txt --no-build-isolation

Tested on Ubuntu 20.04

**Comment by alexhuntley** [comment]
What error are you getting?

**Comment by wbernard** [comment]
I tried to reproduce it again, but it's no longer happening. Sorry about the noise :)

**Comment by alexhuntley** [comment]
Not a problem :)
