### ISSUE TITLE
Circle formula?

### ISSUE THREAD

**Issue by tommyxu** [alexhuntley/Plots#14]
It seems
x^2+y^2=4
doesn't work properly. Any support?

**Comment by alexhuntley** [comment]
Currently there's no support for implicit equations. It wouldn't be a HUGE amount of work, but the rendering algorithm in the shader, among other things, would need changes. But it is definitely something I'd like to do at some point.

**Comment by alexhuntley** [comment]
Fixed in eb06597. Do try it out, and it'll be in version 0.7.0.
