### ISSUE TITLE
Show axis coordinates

### ISSUE THREAD

**Issue by 12people** [alexhuntley/Plots#15]
It's hard to get a good idea of the scale of the graphs without having at least some x and y values as a foundation. It'd be great if the x and y axis were both labeled with coordinates at regular intervals. Those intervals should depend on the scale of zoom, so that they're easily legible, but not sparse enough to be unhelpful.

**Comment by alexhuntley** [comment]
This is a good idea. Unfortunately it seems that it will take some effort to implement text rendering inside the GL view. Hopefully I will find time to do this at some point.

**Comment by alexhuntley** [comment]
Fixed in b27b0c9, which will be in the next release.
