### ISSUE TITLE
In-tree flatpak manifest 

### ISSUE THREAD

**Issue by bilelmoussaoui** [alexhuntley/Plots#2]
It's useful for a clone, build, run with GNOME Builder or VSCode (or any IDE that does support Flatpak in the future) :) 

It can also be used for CI

**Comment by alexhuntley** [comment]
The file [com.github.alexhuntley.Plots.yaml](https://github.com/alexhuntley/Plots/blob/main/com.github.alexhuntley.Plots.yaml) already exists in the tree, does anything need to change?

**Comment by bilelmoussaoui** [comment]
Ah, Builder doesn't have YAML support yet :(
