### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by airon90** [alexhuntley/Plots#20]
Some keys are translateable. How can I translate this software?

**Comment by alexhuntley** [comment]
There is no translation functionality yet... which keys did you have in mind?

**Comment by airon90** [comment]
"Help" and Help files, "About Plots", ...

**Comment by ovari** [comment]
Would the translations be available on [Weblate](https://hosted.weblate.org/)? Thank you

**Comment by ovari** [comment]
The name of the program.

![image](https://user-images.githubusercontent.com/17465872/133328003-fa7e9acb-2f41-4554-889f-afc5e5a05464.png)

Thank you

**Comment by alexhuntley** [comment]
7d65740 introduces translation support (initially just a French translation). Please feel free to add translations in your own languages. To create the `.po` and `.mo` files, please look at https://stackoverflow.com/a/67496139.

I'll look into translating help files and Weblate.

**Comment by ovari** [comment]
> I'll look into translating help files and Weblate.

Thank you

**Comment by alexhuntley** [comment]
I've added Plots to [Hosted Weblate](https://hosted.weblate.org/engage/plots/). Hopefully they will approve the project, but it should work in the meantime.

I'm not sure what to do about translating the help files. It seems Weblate is more for translating individual strings rather than whole documents.

Any suggestions?

**Comment by ovari** [comment]
Have you contacted Weblate about what they recommended if Weblate is not a solution?

**Comment by ovari** [comment]
Can this issue be closed as translations for the main application and Help files are now on Weblate at:
https://hosted.weblate.org/projects/plots/

What do you think?

Thank you

**Comment by alexhuntley** [comment]
Weblate is indeed working well, so I will close this.
