### ISSUE TITLE
Create Settings

### ISSUE THREAD

**Issue by airon90** [alexhuntley/Plots#23]
Is it possible to have a setting section? I'd like to choose colors of axis and background (night mode) and I'd like to turn on number on the default grid

**Comment by alexhuntley** [comment]
The background should change if you change the system GTK theme to a dark one; is it really necessary to have a night mode specifically for this app?

The main branch now has axis labels. They'll be in the next release.

**Comment by airon90** [comment]
> The background should change if you change the system GTK theme to a dark one;

No, background of the cartesian plane doesn't change. It just changes the hamburger menu.

> is it really necessary to have a night mode specifically for this app?

I think that it could be nice to have the possibility to change the color of the plane and axis and it would be better if there is a default option for night mode (other than actual set of colors)

**Comment by alexhuntley** [comment]
> No, background of the cartesian plane doesn't change.

You're right, I was wrong.

> it would be better if there is a default option for night mode (other than actual set of colors)

I'm not sure I understand what you meant by this. If I make the plane and axes change colour to match the GTK light/dark setting, like the rest of the app currently does, would that be good enough? Or do you want to choose the light or dark mode independently of the system theme?

**Comment by airon90** [comment]
> I'm not sure I understand what you meant by this. If I make the plane and axes change colour to match the GTK light/dark setting, like the rest of the app currently does, would that be good enough? Or do you want to choose the light or dark mode independently of the system theme?

*I* would use default light/dark color palette but I suppose that somebody could like to change default colours

**Comment by alexhuntley** [comment]
Plots 0.7.0 introduced a settings window, so I'm considering this done. If you think any additional controls should be added to it, then please create a new issue.
