### ISSUE TITLE
Clarification about dependencies

### ISSUE THREAD

**Issue by apandada1** [alexhuntley/Plots#26]
Right now, plot fails to build in Arch Linux and Ubuntu with the following error.

    ModuleNotFoundError: No module named 'glm'

Is it this library? https://pypi.org/project/glm/
Is it something else?

**Comment by alexhuntley** [comment]
Apologies! I've added two new dependencies:

- https://pypi.org/project/PyGLM/
- https://pypi.org/project/freetype-py/

I should probably have added them to `setup.py`, but was waiting for the next release as I wasn't certain about them.

I don't think PyGLM exists in the Ubuntu repos, so you may have to package it... sorry :sweat_smile: 

I'll update `setup.py` now.

**Comment by alexhuntley** [comment]
Should be fixed in 50abc74. Does it work?

**Comment by apandada1** [comment]
I will try to create a debian package for PyGLM (Arch does not have a package either). Thanks.
