### ISSUE TITLE
Desktop file description/comment

### ISSUE THREAD

**Issue by ovari** [alexhuntley/Plots#31]
Where is the Desktop file so that the description/comment can be:

1. added
![kép](https://user-images.githubusercontent.com/17465872/133870213-d1d8030a-42fb-4c42-b165-a4511aa6d5e0.png)

2. localised
https://github.com/alexhuntley/Plots/issues/20

Thank you

**Comment by apandada1** [comment]
> Where is the Desktop file so that the description/comment can be:

Depends on installation method.

**Comment by alexhuntley** [comment]
The `.desktop` file is [here](https://github.com/alexhuntley/Plots/blob/main/res/com.github.alexhuntley.Plots.desktop) if you wish to add a description.

As for translations, I'm not sure how it's supposed to be done, but I would suggest looking at https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#localized-keys.
