### ISSUE TITLE
Option to increase line width

### ISSUE THREAD

**Issue by mskf1383** [alexhuntley/Plots#52]
Hi
The plots lines are very narrow and hard to see.
It is good to add an option to increse its width.
Thanks!

**Comment by jsgadas** [comment]
Hi, 

It would be really nice if this feature could be added in the future, I'm not sure how hard would it be to implement that support though, but just increase a little bit the line width already improves a lot the readability, just like we can see on demos (please, see attached).

Thanks

![image](https://user-images.githubusercontent.com/38897885/147880865-a81be644-40d0-40b5-8e04-e720f7924383.png)

**Comment by alexhuntley** [comment]
Hi, I'll look into it.

I suspect the main problem will be designing and implementing a UI to adjust the line width.

**Comment by alexhuntley** [comment]
I've implemented this, it'll be in version 0.7.0
