### ISSUE TITLE
Strange artefacting when doing y = x^(4/3)

### ISSUE THREAD

**Issue by Newbytee** [alexhuntley/Plots#55]
Screenshot speaks for itself I think:

![image](https://user-images.githubusercontent.com/4428753/148652666-def7edac-593e-482c-9cea-45c196c01bc3.png)

This only happens on my laptop which uses Intel graphics (Intel HD 5000). My desktop, which uses NVIDIA graphics with the proprietary driver version 495.46, does not exhibit this issue:

![image](https://user-images.githubusercontent.com/4428753/148653268-197de492-45b2-469d-95f0-084e013d38e1.png)

Plots was installed from Flathub on both systems.

**Comment by alexhuntley** [comment]
Interesting, I'm running on an AMD mobile APU so I haven't seen this behaviour.

Exponents are currently calculated in GLSL using [mypow](https://github.com/alexhuntley/Plots/blob/a1ae61fc1cd0791e968d9ca3e49012d783668823/plots/shaders/fragment.glsl#L73).

Currently this doesn't return anything if `x` is negative and `y` is not an integer, so I think we're seeing undefined behaviour in the shader. Ideally we could return a NaN in this case, but according to [this Stackoverflow answer](https://stackoverflow.com/a/37532994) that is not portable...

**Comment by alexhuntley** [comment]
Hopefully should be fixed in a3578b7, please see if that works better.

**Comment by Newbytee** [comment]
Can I somehow get a Flatpak artefact from that build? I see there's a Flatpak Builder job, but I don't see any output. I'm not very familiar with GitHub actions however.

**Comment by alexhuntley** [comment]
I'll be releasing a new version in a few days so it's probably just easiest for you to use that?

**Comment by Newbytee** [comment]
Hm, i just built the latest master locally and the artefacting is still there unfortunately.

**Comment by Newbytee** [comment]
Sorry, false alarm. I only built the Flatpak and forgot to install it. I can confirm that this issue is fixed in the master branch. Nice job!

**Comment by alexhuntley** [comment]
Great, thank you!

**Comment by alexhuntley** [comment]
My original fix has caused other issues (see #68), and so I've tried another approach. Please check if there are any problems for you on version 0.8.1.

**Comment by Newbytee** [comment]
Looks just fine on 0.8.1 from Flathub!

**Comment by alexhuntley** [comment]
Great, thanks!
