### ISSUE TITLE
Color picker improvements

### ISSUE THREAD

**Issue by tronta** [alexhuntley/Plots#56]
What do you think about making the color selection task simpler by converting the color selection to a popup dialog?
![grafik](https://user-images.githubusercontent.com/5135577/150578524-f3349bc6-d7c8-41c9-8d6a-cede4494ebea.png)

It would make imho the mouse travel shorter and the selection more intuitive.

**Comment by alexhuntley** [comment]
Yes I like this idea. The current solution just uses the default GTK3 colour picker because it's easy to code, but I'll eventually code a custom picker. Maybe I should port Plots to GTK4 first though.

Apart from smaller size and placing in a popover, are any other changes desired? Is it worth recreating the custom colour picker, or is the preset palette enough?

**Comment by apandada1** [comment]
> Maybe I should port Plots to GTK4 first though.

Is it really necessary to port to GTK4? Most themes don't yet support GTK4, and it does not look very nice outside GNOME. Support for GTK3 is not going away anytime soon. Right now, Plot works quite well, so why change it for the sake of change...

**Comment by tronta** [comment]
> Apart from smaller size and placing in a popover, are any other changes desired? Is it worth recreating the custom colour picker, or is the preset palette enough?

I would not make it too complicated. The colors a just there to distinguish some plots.

**Comment by alexhuntley** [comment]
> Is it really necessary to port to GTK4? Most themes don't yet support GTK4, and it does not look very nice outside GNOME. Support for GTK3 is not going away anytime soon. Right now, Plot works quite well, so why change it for the sake of change...

We can't stay on GTK3 forever, but you're right that there is no great rush. I'm just unsure about writing new features if they'll just need to be rewritten for GTK4 anyway.

> Unlike GTK2 --> GTK3 transition, GTK3-->GTK4 is very different, and GTK3 will remain there, because complex apps like GIMP, Libreoffice of Inkscape can't work without menus, which GTK4 does not support.

AFAIK Plots isn't using any deprecated UI elements like menus, so porting shouldn't be too painful. That being said, it might make sense to instead just rewrite it from scratch for GTK4 e.g. in Rust or C++.

**Comment by alexhuntley** [comment]
The feature is now in the `main` branch, and will be in a release soon. Let me know what you think :)

**Comment by tronta** [comment]
Awesomely awesome!

**Comment by alexhuntley** [comment]
I thought so too, and tried to do that. However, the custom colors can take up 9 columns, regardless of how wide the palette is. I wasn't able to find a way to change it (or disable the custom colors entirely).

I guess the correct solution would be to replace the GtkColorChooserWidget with a custom widget, but that is a bigger job.
