### ISSUE TITLE
Set limits of how much the user can zoom in

### ISSUE THREAD

**Issue by SViN24** [alexhuntley/Plots#58]
Right now the user can zoom in a lot in the application making it so that you can get buggy graphics(appearing on scales smaller than 5e-36)
This is probably a limitation of GTK 

https://user-images.githubusercontent.com/51864332/152303517-47069ff4-177f-4a00-8292-5e5ce631603e.mp4

**Comment by alexhuntley** [comment]
Yes this needs fixing. I think it is probably due to using single-precision floats in the GLSL shaders. I'll have a think.
