### ISSUE TITLE
Migration to GTK 4.0 / Libadwaita

### ISSUE THREAD

**Issue by ericlesslie** [alexhuntley/Plots#65]
Interested to know if migration to GTK 4.0 or Libadwaita, as a replacement for Handy, is in the development roadmap. This is more of a feature request more than anything.

**Comment by alexhuntley** [comment]
It's something I'd like to do eventually, but it's probably a lot of work...

**Comment by apandada1** [comment]
> It's something I'd like to do eventually, but it's probably a lot of work...

Is it necessary? GTK3 will not be discontinued anytime soon (at least, not unless GIMP and Libreoffice migrate to GTK4). The current version of Plots does its job well, and it does not look out of place in GNOME desktop either.

**Comment by alexhuntley** [comment]
It doesn't look out of place in GNOME yet, but it will eventually, once the other apps are ported.

**Comment by Newbytee** [comment]
> > It's something I'd like to do eventually, but it's probably a lot of work...
> 
> Is it necessary? GTK3 will not be discontinued anytime soon (at least, not unless GIMP and Libreoffice migrate to GTK4). The current version of Plots does its job well, and it does not look out of place in GNOME desktop either.

It would probably help performance.

**Comment by alexhuntley** [comment]
I've been working on this on a local branch, and it's now pretty much ready.

I think I'll make one more GTK3 release (from the current `main` branch) and then merge the GTK4 port and release that.

**Comment by alexhuntley** [comment]
The GTK 4 port was released as 0.8.0.
