### ISSUE TITLE
make all colors dark/light mode aware

### ISSUE THREAD

**Issue by tronta** [alexhuntley/Plots#71]
currently only black (white) is only dark/light mode aware.

It would be great to have all colors be mode aware.

Proposal:
Define for the light mode a set of dark colors (maybe remove yellow, at it is not really visible) on white background.
Then define for each color a lighter version for the dark mode (maybe it is not needed for medium bright colors)

With this, one could switch between the different modes, without adjusting the colors of the plots.

**Comment by alexhuntley** [comment]
Thanks for the suggestion. I implemented this in 022efe9. I kept the yellow in the end, but using a darker shade, so it should be visible enough on the light background.

**Comment by tronta** [comment]
Looks nice. Thanks a lot
