### ISSUE TITLE
plots are under helpers

### ISSUE THREAD

**Issue by mskf1383** [alexhuntley/Plots#76]
Drawed plots are under helper lines:
![نماگرفت از 2022-09-22 09-26-48](https://user-images.githubusercontent.com/50908329/191671413-b184e793-1b10-48a1-a74a-0ac5bf5c88d9.png)

**Comment by alexhuntley** [comment]
Thanks for the suggestion. I've fixed this in 8e8724f, but note that the axis labels are still above everything else.
