### ISSUE TITLE
Hungarian translations of Help files on Weblate complete

### ISSUE THREAD

**Issue by ovari** [alexhuntley/Plots#79]
The recent release of [Plots on Flathub](https://flathub.org/apps/details/com.github.alexhuntley.Plots) didn't include the partially complete Help file translations.

1. Does the CI need to be updated so that updates to the Help files are included with new releases of the main Plots program?

2. Can the Hungarian Help file translations please be merged into the Plots program and released on Flathub?

Thank you

**Comment by alexhuntley** [comment]
>     1. Does the CI need to be updated so that updates to the Help files are included with new releases of the main Plots program?
Not anymore; I did this in a5480101e2e0213db3eb1bf79d1bd9ba1082e8e3, which is in release 0.8.3 on Flathub.

>     2. Can the Hungarian Help file translations please be merged into the Plots program and released on Flathub?
It seems they've already been merged (this happens automatically after around 24 hours) and will be included in the next release.
