### ISSUE TITLE
Sqrt is not following completely dark mode

### ISSUE THREAD

**Issue by tronta** [alexhuntley/Plots#81]
The horizontal bar of the square root is displayed black in dark mode.
![image](https://user-images.githubusercontent.com/5135577/192129003-9f64e4ac-d9e6-4df1-a678-c1b1a35a25cd.png)
![image](https://user-images.githubusercontent.com/5135577/192129008-f937767e-5b4a-48bc-9865-82feb5f4f36b.png)

**Comment by alexhuntley** [comment]
Nice spot, thanks! Fixed in 5110c8bf64b8cd5dd9285cb05acd60ad22727414
